### PR TITLE
Cherry Pick #843 Into Master

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test.

**Comment by CodaFi** [comment]
My CI-foo must be weak this morning.

@swift-ci please test

**Comment by parkera** [comment]
Thanks!

**Comment by eosrei** [comment]
FWIW Build on Ubuntu16.04 is still failing with this import in a different file.
```
CoreFoundation/Collections.subproj/CFBasicHash.c:14:10: fatal error: 'Block.h' file not found
#include <Block.h>
         ^~~~~~~~~
18 warnings and 1 error generated.
```

**Comment by parkera** [comment]
I would still expect you to need Block.h to compile CF. I don't expect you to need it to `import Foundation`.
