### ISSUE TITLE
[SR-13745] URLRequest not working in Swift 5.3 on Ubuntu

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-corelibs-foundation#3968]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13745      |
   |Radar             | rdar://problem/70379840         |
   |Original Reporter | urielc (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Foundation    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 237af2d02e69d4345cdef900372d615a

  </details>

**Issue Description:**

my program compiled and worked with Swift 4, but with Swift 5 it doesn't compile, it fails at

StickerDownloader.swift:24:23: error: cannot find 'URLRequest' in scope  
var request = URLRequest(url: url!)  
                           ^\~\~\~\~\~\~\~\~\~

but I didn't find anywhere than URLRequest were deprecated in Swift 5, so what's happen here?  
I have Swift 5.3 on Ubuntu 20.04
