### PR TITLE
[4.2] Ubuntu18.04 fixes for TestURLSession

### PR DESCRIPTION
**Pull request by spevans**
This is a back port of various fixes to allow TestURLSession to work on Ubuntu18.04 without intermittent errors. It includes the following (some required because of what later fixes are based on)

https://github.com/apple/swift-corelibs-foundation/pull/1602
https://github.com/apple/swift-corelibs-foundation/pull/1613
https://github.com/apple/swift-corelibs-foundation/pull/1565
https://github.com/apple/swift-corelibs-foundation/pull/1498
https://github.com/apple/swift-corelibs-foundation/pull/1650

Tested on macOS, Ubuntu 16.04 and Ubuntu 18.04

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by alblue** [comment]
Looks like a test failure:

> 11:56:24 Test Case 'TestURLSession.test_httpRedirectionWithInCompleteRelativePath' started at 2018-06-24 16:56:01.307
> 11:56:24 
> TestFoundation/TestURLSession.swift:887: error: TestURLSession.test_httpRedirectionWithInCompleteRelativePath : XCTAssertEqual failed: ("200") is not equal to ("404") - HTTP response code is not 200
>

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@spevans Can you look into this test failure? 

```
Test Case 'TestURLSession.test_httpRedirectionWithInCompleteRelativePath' started at 2018-08-01 21:05:45.164
TestFoundation/TestURLSession.swift:879: error: TestURLSession.test_httpRedirectionWithInCompleteRelativePath : XCTAssertEqual failed: ("200") is not equal to ("404") - HTTP response code is not 200
Test Case 'TestURLSession.test_httpRedirectionWithInCompleteRelativePath' failed (0.021 seconds)
```

**Comment by spevans** [comment]
@shahmishal Im just rebasing and testing locally now, If I remember correctly this actually worked ok on my Ubuntu18 server so it may be an issue with Ubuntu16. Is it possible to use swift-ci to direct tests to the individual Ubuuntu18/16/14 servers? I don't want to get this working then find it breaks on Ubuntu14 after merging as is sometimes the case.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by spevans** [comment]
At the moment this PR tests successfully on my local 16.04 and 18.04 test servers so it might take a while to figure out the issue on the CI server. Im just testing on 14.04 to see if that shows up the issue

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
The test passed with the fix https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-foundation-PR-Linux/1190
I just need to create a PR for it and get it reviewed, merged into `master` first.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@shahmishal Looks good now

**Comment by spevans** [comment]
@swift-ci please test and merge
