### PR TITLE
Add tests for `URLSession._MultiHandle` Windows issue

### PR DESCRIPTION
**Pull request by lxbndr**
This adds test cases for #4791.

Test HTTPServer needs to be reconfigured (we need synchronous processing and minimal listening socket backlog) for one of the test scenarios, so there are options now.

- `test_httpTimeout` - former `test_timeoutInterval`, is adjusted to actually test for timeout (it was falsely detecting connection error as expected result)
- `test_connectTimeout` - tests a specific scenario, when the socket is timing out on connection attempt. Seems like with recent cURL library update this now works same way as http timeout, but in the past there was difference, so it is good thing to test
- `test_repeatedRequestsStress` - included only in Windows suite, does a heavy pressure on URLSession/Dispatch using small packs of simultaneous requests, repeated lot of times. There are a bit of randomness, but I find 3000 cycles enough to reproduce crash on my machine. In most of cases it fails on first 300-500 cycles.

macOS system Foundation runs these tests perfectly (btw did we lose Darwin Compatibility Tests target?), but for SwiftFoundation on macOS the `test_repeatedRequestsStress` is surprisingly way slower (I'd say x10 slower) than even on Windows. Anyway, this particular test is intended only for testing against socket reuse on Windows.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by lxbndr** [comment]
```
/Users/ec2-user/jenkins/workspace/swift-corelibs-foundation-PR-macOS/branch-main/swift-corelibs-foundation/CoreFoundation/PlugIn.subproj/CFBundle_Locale.c:151:70: error: initializer element is not a compile-time constant
    static CFStringRef const __CFBundleCommonLanguageNamesArray[] = {CFSTR("English"), CFSTR("French"), CFSTR("German"), CFSTR("Italian"), CFSTR("Dutch"), CFSTR("Spanish"), CFSTR("Japanese")};
```
This part works in Xcode 14.2, but not in Xcode 15. Not related to the changes in this PR.

**Comment by lxbndr** [comment]
Closing, as all relevant code is merged as part of other PR
